# Generated by Django 5.0.1 on 2024-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.grade', verbose_name='Класс/уровень обучения'),
        ),
    ]
