# Generated by Django 5.0.1 on 2024-02-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_grade_customuser_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.grade', verbose_name='Класс/уровень обучения'),
        ),
    ]
