# Generated by Django 5.0.1 on 2024-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='user_answers',
            field=models.JSONField(default=dict, verbose_name='Ответы пользователя'),
        ),
    ]
